In [64]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import random
import pickle

In [65]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
import time
import pickle

In [66]:
DATADIR = "C:/script/python/MachineLearning/Main/SDeepLearningTensorFlowKeras/Pets/PetImages/"
CATEGORIES = ["Dog", "Cat"]

In [67]:
training_data = []

IMG_SIZE = 50

In [68]:
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category)
        print(path)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img),  cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass

In [69]:
create_training_data()

C:/script/python/MachineLearning/Main/SDeepLearningTensorFlowKeras/Pets/PetImages/Dog
C:/script/python/MachineLearning/Main/SDeepLearningTensorFlowKeras/Pets/PetImages/Cat


In [70]:
print(len(training_data))

24946


In [71]:
random.shuffle(training_data)
for sample in training_data[:10]:
    print(sample[1])

1
0
0
0
0
1
1
0
1
0


In [72]:
X = []
y =[]

In [73]:
for features, label in training_data:
    X.append(features)
    y.append(label)

In [74]:
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

In [75]:
pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

In [76]:
pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [77]:
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)
print(X[1])

[[[ 32]
  [ 23]
  [ 29]
  ...
  [109]
  [ 62]
  [ 94]]

 [[ 40]
  [116]
  [ 74]
  ...
  [ 78]
  [ 80]
  [ 91]]

 [[238]
  [138]
  [115]
  ...
  [119]
  [111]
  [249]]

 ...

 [[ 43]
  [ 85]
  [ 81]
  ...
  [ 56]
  [ 59]
  [246]]

 [[ 62]
  [ 57]
  [ 24]
  ...
  [ 72]
  [159]
  [244]]

 [[ 39]
  [ 29]
  [ 58]
  ...
  [ 71]
  [221]
  [242]]]


In [78]:
pickle_in = open("y.pickle", "rb")
y = pickle.load(pickle_in)
print(y[1])

0


In [79]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

In [80]:
X = X/255.0

In [81]:
model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [82]:
model.fit(X, y, batch_size=32, epochs=10, validation_split=0.3)

Train on 17462 samples, validate on 7484 samples
Epoch 1/10
17462/17462 [==============================] - 8s 466us/sample - loss: 0.6327 - acc: 0.6349 - val_loss: 0.5661 - val_acc: 0.7104
Epoch 2/10
17462/17462 [==============================] - 8s 438us/sample - loss: 0.5306 - acc: 0.7342 - val_loss: 0.5110 - val_acc: 0.7473
Epoch 3/10
17462/17462 [==============================] - 8s 447us/sample - loss: 0.4695 - acc: 0.7759 - val_loss: 0.4787 - val_acc: 0.7682
Epoch 4/10
17462/17462 [==============================] - 8s 440us/sample - loss: 0.4223 - acc: 0.8062 - val_loss: 0.4940 - val_acc: 0.7652
Epoch 5/10
17462/17462 [==============================] - 8s 450us/sample - loss: 0.3776 - acc: 0.8285 - val_loss: 0.4727 - val_acc: 0.7722
Epoch 6/10
17462/17462 [==============================] - 8s 432us/sample - loss: 0.3290 - acc: 0.8564 - val_loss: 0.4755 - val_acc: 0.7878
Epoch 7/10
17462/17462 [==============================] - 8s 438us/sample - loss: 0.2732 - acc: 0.8836 - val_lo

In [83]:
NAME =  "Cats-vs-dogs-cnn-{}".format(int(time.time()))

tensorboard = TensorBoard(log_dir='logs/{}'.format(NAME))

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

In [84]:
model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

# model.add(Dense(64))
# model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3, callbacks=[tensorboard])

Train on 17462 samples, validate on 7484 samples
Epoch 1/3
17462/17462 [==============================] - 8s 436us/sample - loss: 0.6513 - acc: 0.6136 - val_loss: 0.6225 - val_acc: 0.6527
Epoch 2/3
17462/17462 [==============================] - 7s 401us/sample - loss: 0.5794 - acc: 0.7011 - val_loss: 0.5680 - val_acc: 0.7035
Epoch 3/3
17462/17462 [==============================] - 7s 402us/sample - loss: 0.5293 - acc: 0.7424 - val_loss: 0.5150 - val_acc: 0.7448


In [85]:
# dense_layers = [0,1,2]
# layer_sizes = [32, 64, 128]
# conv_layers = [1, 2, 3]
#
# for dense_layer in dense_layers:
#     for layer_size in layer_sizes:
#         for conv_layer in conv_layers:
#             NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
#             print(NAME)

In [86]:
dense_layers = [0, 1, 2]
layer_sizes = [32, 64, 128]
conv_layers = [1, 2, 3]

In [87]:

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

            model = Sequential()

            model.add(Conv2D(layer_size, (3, 3), input_shape=X.shape[1:]))
            model.add(Activation('relu'))
            model.add(MaxPooling2D(pool_size=(2, 2)))

            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3, 3)))
                model.add(Activation('relu'))
                model.add(MaxPooling2D(pool_size=(2, 2)))

            model.add(Flatten())

            for _ in range(dense_layer):
                model.add(Dense(layer_size))
                model.add(Activation('relu'))

            model.add(Dense(1))
            model.add(Activation('sigmoid'))

            tensorboard = TensorBoard(log_dir="abunchoflogs/{}".format(NAME))

            model.compile(loss='binary_crossentropy',
                          optimizer='adam',
                          metrics=['accuracy'],
                          )

            model.fit(X, y,
                      batch_size=32,
                      epochs=3,
                      validation_split=0.3,
                      callbacks=[tensorboard])

model.save('64x3-CNN.model')

1-conv-32-nodes-0-dense-1569281649
Train on 17462 samples, validate on 7484 samples
Epoch 1/3
17462/17462 [==============================] - 2s 143us/sample - loss: 0.6226 - acc: 0.6523 - val_loss: 0.5843 - val_acc: 0.7022
Epoch 2/3
17462/17462 [==============================] - 2s 124us/sample - loss: 0.5663 - acc: 0.7121 - val_loss: 0.5580 - val_acc: 0.7159
Epoch 3/3
17462/17462 [==============================] - 2s 127us/sample - loss: 0.5275 - acc: 0.7426 - val_loss: 0.5657 - val_acc: 0.7032
2-conv-32-nodes-0-dense-1569281663
Train on 17462 samples, validate on 7484 samples
Epoch 1/3
17462/17462 [==============================] - 3s 179us/sample - loss: 0.6406 - acc: 0.6286 - val_loss: 0.5960 - val_acc: 0.6832
Epoch 2/3
17462/17462 [==============================] - 3s 149us/sample - loss: 0.5520 - acc: 0.7219 - val_loss: 0.5260 - val_acc: 0.7397
Epoch 3/3
17462/17462 [==============================] - 3s 145us/sample - loss: 0.5028 - acc: 0.7578 - val_loss: 0.5015 - val_acc: 0.756

17462/17462 [==============================] - 6s 326us/sample - loss: 0.6608 - acc: 0.5949 - val_loss: 0.6265 - val_acc: 0.6633
Epoch 2/3
17462/17462 [==============================] - 5s 286us/sample - loss: 0.5855 - acc: 0.6908 - val_loss: 0.5621 - val_acc: 0.7103
Epoch 3/3
17462/17462 [==============================] - 5s 286us/sample - loss: 0.5261 - acc: 0.7389 - val_loss: 0.5251 - val_acc: 0.7388
3-conv-128-nodes-1-dense-1569282037
Train on 17462 samples, validate on 7484 samples
Epoch 1/3
17462/17462 [==============================] - 6s 340us/sample - loss: 0.6440 - acc: 0.6179 - val_loss: 0.5987 - val_acc: 0.6777
Epoch 2/3
17462/17462 [==============================] - 5s 300us/sample - loss: 0.5436 - acc: 0.7264 - val_loss: 0.5349 - val_acc: 0.7312
Epoch 3/3
17462/17462 [==============================] - 5s 293us/sample - loss: 0.4754 - acc: 0.7717 - val_loss: 0.4821 - val_acc: 0.7636
1-conv-32-nodes-2-dense-1569282073
Train on 17462 samples, validate on 7484 samples
Epoch 1